.TH "V" 1
.SH NAME
V \- A concatenative programming language
.SH SYNOPSIS
.B v [source.v]
.SH DESCRIPTION
V is a concatenative (stack based) language. The style is similar
to Postscript and Joy. It provides the primitives for handling stack,
local definitions, modules and exceptions. It is a purely functional
language with single assignment syntax and is based on Combinatory Calculus.
It comes with a simple integrated GC.

.SH FUNCTIONS
.B . Define word
.TP
.B .& Define word in environment
.SH BUGS
