.TH "V" 1
.SH NAME
V \- A concatenative programming language
.SH SYNOPSIS
.B v [source.v]
.SH DESCRIPTION
V is a concatenative (stack based) language. The style is similar
to Postscript and Joy. It provides the primitives for handling stack,
local definitions, modules and exceptions. It is a purely functional
language with single assignment syntax and is based on Combinatory Calculus.
It comes with a simple integrated GC.

.SH FUNCTIONS
.SS .
Define word
.SS .&
Define word in environment
.SS &parent
Get the parent of the provided environment token.
.SS &words
Get the words defined in the provided environment.
.SS &i
Dequote in the provided environment.
.SS &use
Load the library file in provided environment.
.SS &eval
Evaluate the string given in provided environment.
.SS $me
Capture the current environment.
.SS module
Create a module
.SS put
Put the value of token infront to stdout
.SS puts
Put the value of token infront to stdout followed by newline
.SS i
Dequote the provided quote value.
.SS view
Shuffle the stack based on the pattern given.
.SS use
Load the library file.
.SS eval
Evaluate the string given in V.
.SS stack
Collect the tokens in stack to quote.
.SS unstack
Replace the current stack with the tokens in the quote given.
.SS true
Boolean true
.SS false
Boolean false
.SS +
Add two numbers.
.SS -
Subtract two numbers.
.SS *
Multiply two numbers.
.SS /
Divide two numbers.
.SS and
Boolean and. 
.SS or
Boolean or.
.SS not
Boolean not.
.SS choice
Do action based on value of choice.
.SS ifte
If then else.
.SS if
If then.
.SS while
While loop.
.SS =
Equals.
.SS ==
Equals.
.SS !=
Not Equal to.
.SS >
Greater than.
.SS <
Lesser than.
.SS >=
Greater than or equal to.
.SS <=
Lesser than or equal to.
.SS ?stack
Show stack
.SS ?
Peek the last token.
.SS ?frame
Dump the current frame.
.SS int?
Integer predicate.
.SS decimal?
Decimal predicate.
.SS bool?
Boolean predicate.
.SS symbol?
Symbol predicate.
.SS list?
List predicate.
.SS char?
Character predicate.
.SS number?
Number predicate.
.SS string?
String predicate.
.SS abort
Abort execution.
.SS size
Size of the quote given.
.SS in?
Is the token in the quote?.
.SS at
Place the token in the quote.


.SH LIBRARIES
.SS std
Provides definitions for commonly used words.
